version: '3.5'
services:
  app:
    container_name: ${PROJECT_NAME}
    image: ${PROJECT_NAME}
    build:
      context: ./docker
    ports:
      - "8443:443"
    networks:
      docker-network: {}
    volumes:
      - ./app:/var/www

networks:
  docker-network:
    name: ${PROJECT_NAME}
    driver: bridge